### PR TITLE
github: add CMake and Windows workflow

### PR DESCRIPTION
**Pull request by alfredh**
here is my attempt to add Windows/Cmake to github CI.
please note that it currently completes with an error.

regarding the cmake generator, I am not sure which one is best to use.
perhaps ninja or VS project ?

### CODE REVIEW

**Comment by alfredh** [comment]
here is the current build error:

```
ke -S . -B . -G "Visual Studio 17 [2](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:2)022"
2
  cmake -S . -B . -G "Visual Studio 17 2022"
[3](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:3)
  cmake --build .
[4](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:4)
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
[6](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:6)
-- The C compiler identification is MSVC 19.31.31104.0
[7](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:7)
-- Detecting C compiler ABI info
[8](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:8)
-- Detecting C compiler ABI info - done
[9](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:9)
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.31.31[10](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:10)3/bin/Hostx64/x64/cl.exe - skipped
10
-- Detecting C compile features
[11](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:11)
-- Detecting C compile features - done
[12](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:12)
-- Looking for backtrace
[13](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:13)
-- Looking for backtrace - not found
[14](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:14)
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR) 
[15](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:15)
-- Looking for pthread.h
[16](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:16)
-- Looking for pthread.h - not found
[17](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:17)
-- Found Threads: TRUE  
[18](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:18)
-- Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib (found version "1.1.1m")  
[19](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:19)
-- Looking for unistd.h
[20](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:20)
-- Looking for unistd.h - not found
[21](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:21)
-- Configuring done
[22](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:22)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[23](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:23)
Please set them or make sure they are set and tested correctly in the CMake files:
[24](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:24)
Backtrace_LIBRARY (ADVANCED)
[25](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:25)
    linked by target "re-static" in directory D:/a/re/re
[27](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:27)

[28](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:28)
-- Generating done
[29](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:29)
CMake Generate step failed.  Build files cannot be regenerated correctly.
[28](https://github.com/baresip/re/runs/5389492765?check_suite_focus=true#step:4:28)
Error: Process completed with exit code 1.
```

**Comment by sreimers** [comment]
Nice thanks, my fault. Cmake on Windows does not like undefined vars (maybe there is a option to ignore). I think we can exclude Backtrace_LIBRARY from re-static if "WIN32" like for re-shared target.

I prefer currently ninja since it supports parallel builds.

**Comment by sreimers** [comment]
@alfredh can you rebase against main? It should be fixed now.

**Comment by alfredh** [comment]
thanks, it seems to be working now.

you can merge it to main if you want, we can improve it later with "ninja" generator.
I am not really a windows expert BTW.

if there is anyone here with Windows knowledge, please feel free to improve this script.

**Pull request merged**
