### PR TITLE
release v2.8.0

### PR DESCRIPTION
**Pull request by cspiel1**
### Create/Prepare PRs for new Release (re/rem/baresip)
- [x] Update `CHANGELOG.md`
  - Click `Draft a new release` on Release page
  - Fill a new release tag version and title (like v2.4.0)
  - Press `Auto-generate Release notes` 
  - **Save as draft** (don't publish yet)
  - Copy release notes to `CHANGELOG.md`
- [x] Update `debian/changelog`
- [x] Check ABI compatibility (only `re` and `rem` for now)
  - `CMakefile` (Bump PROJECT_SOVERSION)
  - `Makefile` (Bump ABI_MAJOR)
- [x] Comment out PRE Release identifier `-dev`
  - `CMakefile`
  - `Makefile`
- [x] All tests green? [re/rem/retest/baresip]

### Release
- [ ] Merge PRs in this order
  - libre
  - librem
  - retest (needs only a version tag - no PR)
  - baresip
- [ ] Publish draft Releases (follow the same order)
  - Maybe `Auto-generate Release notes` is needed to update (delete last notes first)

### After Release
- [ ] Merge main branches to stable
  - re - https://github.com/baresip/re/compare/stable...main?expand=1
  - rem - https://github.com/baresip/rem/compare/stable...main?expand=1
  - retest - https://github.com/baresip/retest/compare/stable...main?expand=1
  - baresip - https://github.com/baresip/baresip/compare/stable...main?expand=1
- [ ] Bump main branch versions with PRE Release identifier `-dev`
  - `CMakefile`
  - `Makefile`
  - `include/baresip.h` (baresip only)
  
  ---
This list was copied from https://github.com/baresip/re/wiki/Release-Checklist

### CODE REVIEW

**Comment by cspiel1** [comment]
Was not sure, if the step "Save as draft" creates a draft PR already and branch already. But it didn't. So will proceed in my branch.

**Comment by cspiel1** [comment]
ABI version has to be incremented. At least because of:
`re_http, re_rtp, ...`

In the future, should we increment it in the PR that breaks the ABI?

**Comment by sreimers** [comment]
> In the future, should we increment it in the PR that breaks the ABI?

This would lead to a high ABI version number, at the moment we have multiple ABI breaks per release. Its normal that dev releases break the ABI, so IMHO it should only increased on release.

> In the release comment it out. So in CMakeLists.txt no `PROJECT_VERSION_FULL` is set?

Sorry my fault, we need this on release:

`set(PROJECT_VERSION_FULL ${PROJECT_VERSION})`

**Comment by cspiel1** [comment]
@sreimers I think that I made some kind of mistake now. In `retest` seems that old tags had not been all in github and a lot of old tags where created remote:
```
git push --tags
...
 * [new tag]         v0.4.15 -> v0.4.15
 * [new tag]         v0.4.16 -> v0.4.16
 * [new tag]         v0.4.17 -> v0.4.17
 * [new tag]         v0.5.0 -> v0.5.0
 * [new tag]         v0.5.1 -> v0.5.1
 * [new tag]         v0.5.2 -> v0.5.2
 * [new tag]         v0.5.3 -> v0.5.3
 * [new tag]         v0.5.4 -> v0.5.4
 * [new tag]         v0.5.5 -> v0.5.5
 * [new tag]         v0.5.6 -> v0.5.6
 * [new tag]         v0.5.7 -> v0.5.7
 * [new tag]         v0.5.8 -> v0.5.8
 * [new tag]         v0.5.9 -> v0.5.9
 * [new tag]         v0.6.0 -> v0.6.0
 * [new tag]         v0.6.1 -> v0.6.1
 * [new tag]         v1.0.0 -> v1.0.0
 * [new tag]         v1.1.0 -> v1.1.0
 * [new tag]         v2.0.0 -> v2.0.0
 * [new tag]         v2.0.1 -> v2.0.1
 * [new tag]         v2.0.1-dev10 -> v2.0.1-dev10
 * [new tag]         v2.0.1-dev11 -> v2.0.1-dev11
 * [new tag]         v2.0.1-dev12 -> v2.0.1-dev12
 * [new tag]         v2.0.1-dev13 -> v2.0.1-dev13
 * [new tag]         v2.0.1-dev14 -> v2.0.1-dev14
 * [new tag]         v2.0.1-dev15 -> v2.0.1-dev15
 * [new tag]         v2.0.1-dev17 -> v2.0.1-dev17
 * [new tag]         v2.0.1-dev7 -> v2.0.1-dev7
 * [new tag]         v2.0.1-dev8 -> v2.0.1-dev8
 * [new tag]         v2.0.1-dev9 -> v2.0.1-dev9
 * [new tag]         v2.1.1 -> v2.1.1
 * [new tag]         v2.2.0 -> v2.2.0
 * [new tag]         v2.2.1 -> v2.2.1
 * [new tag]         v2.2.2 -> v2.2.2
 * [new tag]         v2.3.0 -> v2.3.0
 * [new tag]         v2.8.0 -> v2.8.0
```

Does it matter?

**Comment by sreimers** [comment]
> Does it matter?

I think not, looks ok to me. I see only v2.8.0 as new tag.

**Comment by cspiel1** [comment]
> Check ABI compatibility (only re and rem for now)
CMakeLists.txt got a `PROJECT_SOVERSION` yesterday. No counterpart in Makefile.

I'll inc ABI version because some enums became new values.

**Pull request merged**
