### PR TITLE
merge rem into re

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by robert-scheck** [comment]
May I kindly ask for some explanation? I'm not against this, I just would like to understand _why_ rem will be merged into re.

**Comment by alfredh** [comment]
looks like the MinGW build is failing:

```
CMake Error: The source directory "/home/runner/work/re/re/baresip-win32/rem" does not exist.
```

I have also made a PR for baresip-win32 but I am not sure if it is picked up?

**Comment by sreimers** [comment]
> I have also made a PR for baresip-win32 but I am not sure if it is picked up?

I think its not, can you try with dependency helper:

```diff
--- a/.github/workflows/mingw.yml
+++ b/.github/workflows/mingw.yml
@@ -34,9 +34,14 @@ jobs:
         repo: https://github.com/baresip/retest
         secret: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: "clone baresip-win32 repo"
+    - uses: sreimers/pr-dependency-action@v0.5
+      with:
+        name: baresip-win32
+        repo: https://github.com/baresip/baresip-win32
+        secret: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: "baresip-win32 repo"
       run: |
-        git clone https://github.com/baresip/baresip-win32.git
         mv rem baresip-win32/
         mv retest baresip-win32/
```

**Comment by sreimers** [comment]
> May I kindly ask for some explanation? I'm not against this, I just would like to understand _why_ rem will be merged into re.

from my perspective mainly to simplify maintenance and development, some benefits are:

- We can remove some PR dependency workarounds
- Improve CI Jobs (like coverage, remove redundant jobs)
- One Changelog/Release

**Comment by juha-h** [comment]
Tried on Debian.  Worked OK, but debian/control needs librem dependency removed from line:
```
control:Depends: ${shlibs:Depends}, ${misc:Depends}, librem (>= 2.8.0), libre (>= 2.8.0)
```
Will try later on Android.

**Comment by alfredh** [comment]
related PRs:

https://github.com/baresip/re/pull/683

https://github.com/baresip/retest/pull/184

https://github.com/baresip/baresip/pull/2442

https://github.com/baresip/baresip-win32/pull/10

**Comment by juha-h** [comment]
Now Debian libre build gave these warnings:
```
dpkg-shlibdeps: warning: symbol sqrt used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.14.12.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol sin used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.14.12.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol cos used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.14.12.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol lrint used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.14.12.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol log10 used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.14.12.0 found in none of the libraries
```

**Comment by alfredh** [comment]
looks like linking to libm was missing...

@sreimers should we merge this to main now ?

**Comment by sreimers** [comment]
> @sreimers should we merge this to main now ?

Yes, looks good to me. Thanks!

**Pull request merged**
