### PR TITLE
sipsess: allow sending of "100 Trying" messages

### PR DESCRIPTION
**Pull request by pitti98**
This allows sending "100 Trying" messages

### CODE REVIEW

**Comment by sreimers** [comment]
@maximilianfridrich Can you review this, I'm not sure if "100 Trying" can be used here:

[rfc3262](https://www.rfc-editor.org/rfc/rfc3262#section-3):

>    100 (Trying) responses are hop-by-hop only.  For this reason, the
      reliability mechanisms described here, which are end-to-end,
      cannot be used.

**Comment by maximilianfridrich** [comment]
That is correct, 100 responses may not be sent reliably.

I am wondering, what is the motivation behind this change? @pitti98 If I am not mistaken, 100 Trying responses are usually sent by proxy servers.

[Section 21.1.1 of RFC 3261:](https://www.rfc-editor.org/rfc/rfc3261#section-21.1.1)

> 100 Trying
>    This response indicates that the request has been received by the
>    next-hop server and that some unspecified action is being taken on
>    behalf of this call (for example, a database is being consulted).
>    This response, like all other provisional responses, stops
>    retransmissions of an INVITE by a UAC.  The 100 (Trying) response is
>    different from other provisional responses, in that it is never
>    forwarded upstream by a stateful proxy.

**Comment by alfredh** [comment]
please read the spec carefully regarding 100 usage and 101-199 replies:

https://datatracker.ietf.org/doc/html/rfc3261#section-21.1.1


100 Trying should only be sent by a SIP Proxy...

**Comment by pitti98** [comment]
Basically, we're implementing a SIP-to-something-else gateway, so 100 Trying seemed like a natural choice. I was surprised the library does not allow this. And I see no reason why this should not be allowed, unless the library's purpose is strictly limited to implement a "phone" and nothing else. But it seems powerful enough to implement a server/proxy. We also implemented our own registrar to handle REGISTER messages.
But I guess a 180 would also do the trick.

**Comment by pitti98** [comment]
> please read the spec carefully regarding 100 usage and 101-199 replies:
> https://datatracker.ietf.org/doc/html/rfc3261#section-21.1.1
> 100 Trying should only be sent by a SIP Proxy...

I did read the spec again, and I didn't find any indication for that anywhere. It only says that *stateful proxies* must not forward it (because they generate their own 100 Trying locally). That doesn't mean that only proxies are allowed to send it. Rfc 3261 rather says that stateful proxies behave like UASes in that they generate their own reponses. So any UAS can send a 100 Trying, even a physical phone. It also says that the To-tag may be missing (in the case of a proxy), but the fact that it can contain a to-tag means that it comes from the called UAC, which means it may send a 100 Trying. 

Rfc 3262 says that 100 is excluded from the 100rel mechanism, and that also makes sense because if it doesn't arrive, then the INVITE is simply resent. That also does not mean only proxies may send it.

On the contrary, 3261 specifially says in 17.2.1: 
> When a server transaction is constructed for a request, it enters the
> "Proceeding" state.  The server transaction MUST generate a 100
> (Trying) response unless it knows that the TU will generate a
> provisional or final response within 200 ms, in which case it MAY
> generate a 100 (Trying) response.

and that part is about server transactions in general, not specificly about proxies.

If the library is lacking the ability to send a 100 Trying, then it is missing an important part of the SIP protocol, even when you are not trying to implement a proxy.

We've had this patch in the library for 10 years now and it works. [maximilianfridrich](https://github.com/maximilianfridrich) even confirmed that the code does the right thing.

**Pull request closed without merging**
