### PR TITLE
tls: Send DTLS packets in separate UDP packets

### PR DESCRIPTION
**Pull request by Lastique**
Some SIP terminals don't support multiple DTLS packets in a single UDP packet. This breaks DTLS handshake.

### CODE REVIEW

**Comment by sreimers** [comment]
I wonder if we should make this optional. On a quick baresip <--> baresip test this increases the package quantity from 9 to 21 UDP datagrams (DTLS_SRTP RTP/RTCP Handshake). More pakets that can fail, get lost or reordered and more handshake latency.

CC: @alfredh

**Comment by Lastique** [comment]
The problem is at this point we don't know which terminals have this issue and there seems to be no way to detect it. This is an old patch in our code base, and there's no information on for what terminals the problem was reported. We would have it always enabled. But I'm fine making it optional. Please let me know how I could do this.

**Comment by alfredh** [comment]
the current code is working fine against many DTLS implemenations,
OpenSSL, LibreSSL, Chrome, Firefox etc.

I think you have to prove why it is not working, before making this change

**Comment by Lastique** [comment]
On June 25, 2022 10:31:11 AM "Alfred E. Heggestad" 
***@***.***> wrote:

> the current code is working fine against many DTLS implemenations,
> OpenSSL, LibreSSL, Chrome, Firefox etc.
>
> I think you have to prove why it is not working, before making this change

The problem was not with a software client but a hardware SIP terminal. As 
I said, I have no information on what model or manufacturer it was. I'm not 
sure how I can prove that the problem was real, so feel free to close the 
PR if you think it's not acceptable.

**Comment by sreimers** [comment]
I will close this for now. If you have more details feel free to reopen.

**Pull request closed without merging**
