### PR TITLE
fix client use sub-protocol (Sec-WebSocket-Protocol), server accept response message error

### PR DESCRIPTION
**Pull request by jimying**
when websocket client  connect to server , with sub protocol,   server response 101,  should has header Sec-WebSocket-Protocol

### CODE REVIEW

**Comment by sreimers** [comment]
Currently there is no api to support/handle Websocket Sub-protocols, so I think we can not agree to something that's currently not implemented. Can you describe your use case or problem? I can put Sub-protocol (server+client) support to the roadmap or maybe you can extend this PR (that would be a nice feature).

**Comment by jimying** [comment]
steps to test:
1. use re library write an simple websocket server, listen on port 5000
2. use chrome browser as client,  F12 open console, input
    ws = new WebSocket('ws://127.0.0.1:5000', 'aa')    // sub-protocol
'aa',   when server response 101,  chrome will close websocket connection
    ws = new WebSocket('ws://127.0.0.1:5000')     // without sub-protocol,
all things work right
    ws.send('hello')    // send message

when client has sub-protol,  request message has the head
'Sec-WebSocket-Protocol': 'aa',
server side 101 response message, also should has this head, Otherwise
negotiation fails.


Sebastian Reimers ***@***.***> 于2021年4月2日周五 上午12:32写道：

**Comment by jimying** [comment]
@sreimers hi,  I see the re code , websocket  client connect api,  websock_connect,  should also add  an sub_protocol param, 
which will add the header 'Sec-WebSocket-Protocol'.   i will add this change.

**Comment by jimying** [comment]
@sreimers  I use chrome console to test this feature.   If use  re  library websocket client api  websock_connect() to connect to server,   should  add  the header the head 'Sec-WebSocket-Protocol'.

**Comment by jimying** [comment]
```
err = websock_connect(&test.wc_cli, test.ws,
			      http_cli, uri, 0,
			      cli_websock_estab_handler,
			      cli_websock_recv_handler,
			      cli_websock_close_handler, &test,
			      "User-Agent: %s\r\nSec-WebSocket-Protocol:%s\r\n", custom_useragent,  sub_proto);
```

**Comment by sreimers** [comment]
Your workaround accepts any value of subprotocol and does not check if its really supported.
The RFC says:
```
This enables scripts to both select a subprotocol and be sure that the server agreed to serve that subprotocol.
```

Accepting a subprotocol is only useful if there is full support and a selection mechanism, one use case could be api versioning:
```
ws = new WebSocket('ws://127.0.0.1:5000', 'v1')
ws = new WebSocket('ws://127.0.0.1:5000', 'v2')
```
But at the moment there is no way to specify and select which subprotocol is implemented by the websocket server.

If you need only multiple websocket endpoints you can use `path`:
```
 ws = new WebSocket('ws://127.0.0.1:5000/chat')
 ws = new WebSocket('ws://127.0.0.1:5000/ping')
```

**Comment by jimying** [comment]
```
This enables scripts to both select a subprotocol and be sure that the server agreed to serve that subprotocol.
```
@sreimers  I think it mean before accept client connection,   can check the sub-protocol , to select deny or accept.   The logic should do by app

```
// get sub-protocol from request headers
// and check sub-protocol
if sub-protocol !='xx'
    deny
else
websock_accept()
```

**Comment by jimying** [comment]
webscoket server sample code,   only  allow sub-protocol 'aa'
```c
static void http_req_handler(struct http_conn *conn,
			     const struct http_msg *msg, void *arg)
{
	int err;

    struct websock_conn *wc = NULL;

    /*
	TEST_ASSERT(http_msg_hdr_has_value(msg, HTTP_HDR_USER_AGENT,
					   custom_useragent));
    */
    fprintf(stderr, "path is %.*s\n", (int)msg->path.l, msg->path.p);
    const struct http_hdr *sub_proto_hdr = http_msg_hdr(msg, HTTP_HDR_SEC_WEBSOCKET_PROTOCOL);
    if (!sub_proto_hdr)
    {
        fprintf(stderr, "No sec-websocket-protocol\n");
        http_conn_close(conn);
        return;
    }
    fprintf(stderr, "sec-websocket-protocol is %.*s\n", (int)sub_proto_hdr->val.l, sub_proto_hdr->val.p);
    if (pl_strcasecmp(&sub_proto_hdr->val, "aa"))
    {
        fprintf(stderr, "sub proto is not aa\n");
        http_conn_close(conn);
        return;
    }

    err = websock_accept(&wc, ws, conn, msg,
                         0, srv_websock_recv_handler,
                         srv_websock_close_handler, wc);
    if (err)
    {
        fprintf(stderr, "accept new websock fail, err:%d\n", err);
    }
}

```

**Comment by sreimers** [comment]
I have added [Websocket sub-protocol support](https://github.com/baresip/re/projects/1#card-61947209) to roadmap.

**Pull request closed without merging**
