### PR TITLE
prepare for version 2.3.0

### PR DESCRIPTION
**Pull request by alfredh**
prepare for next release:

We will try to release these projects at the same time:

- re
- rem
- retest
- baresip

### CODE REVIEW

**Comment by sreimers** [comment]
We need a ABI bump (4 -> 5):

`Functions changes summary: 3 Removed, 12 Changed (197 filtered out), 33 Added functions`

**Comment by sreimers** [comment]
https://github.com/baresip/re/blob/main/debian/changelog
https://github.com/baresip/re/blob/main/rpm/re.spec

need a release bump

**Comment by alfredh** [comment]
should we drop the RPM files ? I think the RPM maintainer have their own RPM spec
files which are out of tree ?

**Comment by sreimers** [comment]
> should we drop the RPM files

Yes I think we can remove them.

**Comment by alfredh** [comment]
ok. should be ready to merge now ...

**Pull request merged**
