### PR TITLE
main: add support for external poll

### PR DESCRIPTION
**Pull request by cspiel1**
Adds functions re_prepare_select, re_prepare_poll, re_prepare_epoll and
re_prepare_kqueue for passing external file descriptor polling data to libre.
This can be used in order to run libres file descriptor processing in
the applications thread.

If an application has it's own polling loop, one of the new prepare-functions
will prepare libre for the external polling. In the polling loop the new
function re_process should be called, instead of the blocking function re_main.

Example:
```c
struct epoll_event *events = mem_zalloc(MAXFDS * sizeof(*events), NULL);
int epfd = epoll_create(MAXFDS);

re_prepare_epoll(MAXFDS, events, epfd);
...
while (run)  {
    long int to;
    int n;

    to = re_next_timeout();
    n = epoll_wait(epfd, events, MAXFDS, to ? (int)to : -1);

    re_process(n);
}
```

Note: I realized that this commit should go mainline first. If you find this useful. The PR for the planned real-time polling loop will follow.

### CODE REVIEW

**Comment by sreimers** [comment]
I'm not fully understand this approach.

 `re_thread_init` stores `struct re` in a thread specific store and the new thread can use simply `re_main()` to process thread specific file descriptors already. if `fd_listen` (from network code) is called in the application thread it is stored in the thread specific re poll loop.

**Comment by sreimers** [comment]
I'm not fully understand this approach.

 `re_thread_init` stores `struct re` in a thread specific store and the new thread can use simply `re_main()` to process thread specific file descriptors already. if `fd_listen` (from network code) is called in the application thread it is stored in the thread specific re poll loop.

**Comment by cspiel1** [comment]
An application may combine the processing of multiple libraries in one poll loop. Other libraries have their own software timer implementation. And the application may query the next timeout from each library and pass the minimum to the epoll_wait().

So if the application wants to run `re`, `baresip` and network code of other libs with different software timers in one thread, it is not possible to call `re_main()`.

**Comment by sreimers** [comment]
Thanks for clarification. I don't know your specific mosquitto implementation, the mqtt module in baresip use `mosquitto_socket` and `mosquitto_loop_misc` with tmr for a similar use case.

Would a callback in fd_listen/fd_close maybe enough? So you can register this for your custom eventloop and handle all details there?

**Comment by cspiel1** [comment]
Thanks Sebastian! @fAuernigg an me discussed again about this. We should get rid of this. For now it should be possible to have `re_main()` as top level main loop if it is combined with:
- mosquitto
- glib (for dbus)

But instead become more flexible to decide which `re` tasks to be combined in one thread. Example:
- thread 1: re in libbaresip -> SIP/RTP
- thread 2: re HTTP requests + moqsuitto + glib dbus

So we could add a `re_alloc()` and a parameter `re` to `re_main()` --> `re_main(re)`.

I close this for now and open a new PR. Maybe combined with the "real-time" main loop PR.

**Pull request closed without merging**
