### PR TITLE
sip: reuse transport protocol of first request in dialog (#143)

### PR DESCRIPTION
**Pull request by cspiel1**
This solve a protocol mix during a SIP dialog.

Issue #143.

If answer to question (B) in #143 can be answered with yes, this would be a solution. Any comments?

### CODE REVIEW

**Comment by cspiel1** [comment]
@sreimers Sorry, again I have a problem with the checks. And I don't know how to reproduce it on my dev host.

```
regular tests:       /Users/runner/work/_temp/39168dfa-6fc0-4463-96cf-3829c71c085b.sh: line 5:  7701 Trace/BPT trap: 5       ./retest -r
```

I tried `nektos/act`. But it fails with missing `gcc, clang, wget, make` (`build-essential` form ubuntu).

**Comment by sreimers** [comment]
i'll take a closer look on my macos development environment

**Comment by cspiel1** [comment]
I fixed a illegal write. And did a squash to keep the git log clean. Maybe this solves the failed github workflow.

**Comment by sreimers** [comment]
`make clang` warning:

```
src/sip/request.c:715:3: warning: Value stored to 'req' is never read [deadcode.DeadStores]
                req = mem_deref(req);
                ^     ~~~~~~~~~~~~~~v
```

**Comment by cspiel1** [comment]
Rebased to master.
We have this in our testing since August 18th.
Any more comments?

**Pull request merged**
