### PR TITLE
mem: add error about missing locking

### PR DESCRIPTION
**Pull request by alfredh**
this is a proposal ...

the warning text can be discussed ...

### CODE REVIEW

**Comment by alfredh** [comment]
didnt work:

```
FAILED: CMakeFiles/re-objs.dir/src/main/main.c.obj 
[86](https://github.com/baresip/re/runs/6175251275?check_suite_focus=true#step:4:86)
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\cl.exe  /nologo -DARCH=\"AMD64\" -DHAVE_ATOMIC -DHAVE_INET6 -DHAVE_IO_H -DHAVE_SELECT -DOS=\"Windows\" -DUSE_DTLS -DUSE_OPENSSL -DUSE_OPENSSL_AES -DUSE_OPENSSL_DTLS -DUSE_OPENSSL_HMAC -DUSE_OPENSSL_SRTP -DUSE_TLS -DVERSION=\"2.2.2\" -DVER_MAJOR=2 -DVER_MINOR=2 -DVER_PATCH=2 -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -ID:\a\re\re\. -ID:\a\re\re\include -I"C:\Program Files\OpenSSL-Win64\include" /WX /MDd /Zi /Ob0 /Od /RTC1 /W3 -std:c11 /showIncludes /FoCMakeFiles\re-objs.dir\src\main\main.c.obj /FdCMakeFiles\re-objs.dir\ /FS -c D:\a\re\re\src\main\main.c
[87](https://github.com/baresip/re/runs/6175251275?check_suite_focus=true#step:4:87)
D:\a\re\re\src\main\main.c(203): fatal error C1021: invalid preprocessor command 'warning'
[88](https://github.com/baresip/re/runs/6175251275?check_suite_focus=true#step:4:88)
[49/199] Building C object CMakeFiles\re-objs.dir\src\main\init.c.obj
[89](https://github.com/baresip/re/runs/6175251275?check_suite_focus=true#step:4:89)
[50/199] Building C object CMakeFiles\re-objs.dir\src\main\method.c.obj
```


is there a portable preprocessor command for "warning" ?

**Comment by alfredh** [comment]
do you think that error is too aggressive in mem.c ?




the problem is that for the debug build there is a list of allocated objects,
and if the application is multi-threaded, it needs to have a lock otherwise
it might crash.

this is now solved platforms with pthread and also for Windows.
any other platform is undefined.

**Comment by sreimers** [comment]
yes, `error` is fine for mem.c I think.

**Comment by alfredh** [comment]
if the person building re got the build flags wrong, the build process will not stop.
the alternative is that he will be using a buggy re.


please note that the main.c also needs updating regarding locking for WIN32,
adding INIT_ONCE and CRITICAL_SECTION etc...

**Pull request merged**
