### PR TITLE
cmake/pkgconfig: fix prefix variable

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
Same for `rem`: https://github.com/baresip/rem/pull/109

Is today a release planned?

**Comment by sreimers** [comment]
> Is today a release planned?

No, next week (December 7)

**Comment by cspiel1** [comment]
Okay. Which release cycle do we have now? And why 7th?

**Comment by sreimers** [comment]
5 Weeks (after 3 weeks feature freeze).

https://github.com/baresip/baresip/milestones

**Pull request merged**
