### PR TITLE
sipreg: call response handler also for un-register

### PR DESCRIPTION
**Pull request by cspiel1**
In baresip we want to add new events for the un-register result. Adds also a
new getter function for sipreg->expires to decide if it was the response for
a REGISTER or for an un-REGISTER.

See also baresip PR https://github.com/baresip/baresip/pull/1070!

### CODE REVIEW

**Comment by cspiel1** [comment]
Hi Alfred, this is the first PR that makes a Cisco Mode available. With a successful Unregister success, the presence of a SIP fallback server can be detected like a ping to a SIP Server but without the need to register on all servers in parallel. If the main server goes offline, we already know if a fallback server is available which will be our next main SIP server.

**Comment by alfredh** [comment]
perhaps a better solution is to add a function to explicitly un-register:

```c
void sipreg_unregister(struct sipreg *reg);
```

**Comment by cspiel1** [comment]
> perhaps a better solution is to add a function to explicitly un-register:
> 
> ```c
> void sipreg_unregister(struct sipreg *reg);
> ```

Good advice! We will discuss this and prepare a baresip PR for the Cisco Mode, preferable as module and minimal changes in ua. Here is an article about the Cisco Keep alive mechanism:
https://www.cisco.com/c/en/us/support/docs/collaboration-endpoints/unified-ip-phone-7900-series/200410-Troubleshoot-IP-Phone-Unregistration-A.html#anc11

**Comment by alfredh** [comment]
closing this one.

it is probably better to make a complete patch with cisco mode.
the complete patch can then be tested etc.

**Pull request closed without merging**
