### PR TITLE
merge librem into libre (experiment)

### PR DESCRIPTION
**Pull request by alfredh**
Attempt to simplify things by merging rem into re. Proposal:

API:     re.h and rem.h
Library: libre.so only

### CODE REVIEW

**Comment by alfredh** [comment]
I am working on some new features, including:

- Adding support for Android NDK and arm64 to CI
- Adding support for cppcheck to CI
- Phasing out HAVE_INET6 macro


In all these case it would be more simple if re/rem/retest was one GIT project.
My wish is to have it all in one project and then run this to test it:

```
$ make test
```

Please let me know of your opinions

**Comment by sreimers** [comment]
This remind me of https://github.com/baresip/baresip-libs, but had not enough spare time in the past to complete the migration. At the moment I use this for subdirectory testing. And update manually:

```
git subtree pull --prefix=re https://github.com/baresip/re.git main
git subtree pull --prefix=rem https://github.com/baresip/rem.git main
git subtree pull --prefix=test https://github.com/baresip/retest.git main
```

**Comment by cspiel1** [comment]
Good idea! We use `re` also for non-baresip installations for SW that depends only on `re`, not `rem`. So a `USE_REM` switch or similar might be helpful.

The `baresip-libs` might be an alternative. As result an embedded project might need only one recipe `baresip-libs.bb`.

**Comment by sreimers** [comment]
If we decide to merge `rem` into `re` we should maybe use a subfolder, like `src/rem` or `rem/src`, so its more clear why these functions are prefixed with `rem_` and others not.

**Comment by alfredh** [comment]
great, thanks for the comments ... new PR coming up ...

**Pull request closed without merging**
