### PR TITLE
ice: mDNS refactoring

### PR DESCRIPTION
**Pull request by sreimers**

### CODE REVIEW

**Comment by sreimers** [comment]
I'm a bit unsure how we should handle this nicely. Without Trickle we have to wait for all candidates. But mDNS timeouts are between 3-5 seconds. That's a high startup delay. Especially if hosts are not on the same network. Should we migrate baresip ice to trickle and add only mDNS support there?

**Comment by alfredh** [comment]
There are two ICE stacks, "ice" and "trice".

The latter one has multiple interfaces and supports Trickle ICE, it has been in production
for around 8 years. The long term goal is to merge these 2 stacks into one stack.

We could create a new baresip module `trice.so` and experiment with how it works.

Waiting for all candidates to finish it not so practical, IMHO. You could also add a new flag
to "ice" which says dont wait for all candidates to finish ...

**Comment by alfredh** [comment]
It is also possible to add optional "Trickle Mode" to the current ICE stack, so that we
don't have to wait for all candidate pairs to finish...

**Comment by alfredh** [comment]
There is also another solution, which is to set the mDNS timeout short, e.g. 100ms.

**Comment by sreimers** [comment]
> There is also another solution, which is to set the mDNS timeout short, e.g. 100ms.

Since I had already a 100ms default timeout implemented this workaround was easy. Needs some testing...

**Pull request merged**
