### PR TITLE
Use CMake for debian packages

### PR DESCRIPTION
**Pull request by sreimers**
Tested with Debian 11:

`dpkg-buildpackage -rfakeroot --post-clean`

### CODE REVIEW

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> @juha-h can you test if this works for you?

I pull latest master and then tried to patch it with diff of this pr and
the patch failed:

$ patch -p1 --dry-run < /tmp/522.diff 
checking file CMakeLists.txt
Hunk #1 FAILED at 585.
1 out of 1 hunk FAILED
checking file debian/compat
checking file debian/control
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED
checking file debian/copyright
Hunk #1 FAILED at 1.
1 out of 2 hunks FAILED
checking file debian/libre-dev.cmake-components
The next patch would delete the file debian/libre-dev.dirs,
which does not exist!  Assume -R? [n] ^C

**Comment by sreimers** [comment]
You can checkout the `cmake_debian` branch for testing.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> You can checkout the `cmake_debian` branch for testing.

/usr/src/orig/baresip$ git branch
* main
/usr/src/orig/baresip$ git pull
Already up to date.
/usr/src/orig/baresip$ git checkout cmake_debian
error: pathspec 'cmake_debian' did not match any file(s) known to git

**Comment by sreimers** [comment]
This is only a libre PR, are you try with baresip repo instead?

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> This is only a libre PR, are you try with baresip repo instead?

OK, will try in re.

**Comment by juha-h** [comment]
Debian 11 package build worked with some warnings:

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY

and at the end:

   dh_shlibdeps -O--buildsystem=cmake
dpkg-shlibdeps: warning: symbol dlsym used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol dlopen used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol dlerror used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol dlclose used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries

It was verbose build that generated lots of output.

**Comment by juha-h** [comment]
juha-h writes:

> Debian 11 package build worked with some warnings:
> 
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_EXPORT_NO_PACKAGE_REGISTRY
> 
> and at the end:
> 
>    dh_shlibdeps -O--buildsystem=cmake
> dpkg-shlibdeps: warning: symbol dlsym used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
> dpkg-shlibdeps: warning: symbol dlopen used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
> dpkg-shlibdeps: warning: symbol dlerror used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries
> dpkg-shlibdeps: warning: symbol dlclose used by debian/libre/usr/lib/x86_64-linux-gnu/libre.so.2.7.0 found in none of the libraries

These dh_shlibdeps warnings do not exist in current non-cmake build.

**Comment by sreimers** [comment]
> These dh_shlibdeps warnings do not exist in current non-cmake build.

Should be fixed now.

**Comment by juha-h** [comment]
Yes, now only this warning is left:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
```

**Comment by sreimers** [comment]
> Yes, now only this warning is left:
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_EXPORT_NO_PACKAGE_REGISTRY
> ```

Thanks, I think we can ignore this. we define no cmake exports, so its unused for now.

**Pull request merged**
