### PR TITLE
cmake: use BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by sreimers**
Only build shared or static library (not both).

refs #771 

Breaking change, for static builds `cmake -B build -DBUILD_SHARED_LIBS=OFF` is needed.

### CODE REVIEW

**Comment by alfredh** [comment]
I can try this with Vcpkg
and see if it works.

**Comment by alfredh** [comment]
this looks good.

I tested this patch with Vcpkg and it is working:


https://github.com/microsoft/vcpkg/pull/30859

**Comment by alfredh** [comment]
I guess for Debian packages we would have to compile it twice, one for shared and one for static ?

also another option is to add 2 variables, so it can build both in one go:

```
LIBRE_BUILD_STATIC=OFF|ON
LIBRE_BUILD_SHARED=OFF|ON
```

**Comment by sreimers** [comment]
Yes I think this looks better and is more flexible:  https://github.com/baresip/re/pull/778

**Pull request closed without merging**
