### PR TITLE
release v2.11.0

### PR DESCRIPTION
**Pull request by cspiel1**
checklist: https://github.com/baresip/re/wiki/Release-Checklist

### CODE REVIEW

**Comment by cspiel1** [comment]
Increments also ABI version, because one function was removed:
```patch
-int tls_set_selfsigned(struct tls *tls, const char *cn);
```

**Comment by cspiel1** [comment]
Not sure about the Copyright line in CMakeLists.txt

**Comment by sreimers** [comment]
> Not sure about the Copyright line in CMakeLists.txt

I think it should be enough to bump the copyright year in `LICENSE` and `README`.

Curl for example dropped the copyright years completely (except license): https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/

**Comment by cspiel1** [comment]
And should I revert the lines in CMakeLists.txt?

**Comment by sreimers** [comment]
> And should I revert the lines in CMakeLists.txt?

Yes I think so.

**Comment by cspiel1** [comment]
- When should we append the "-dev" suffix?
- Did you drop already the stable branches/releases?

**Pull request merged**
