### PR TITLE
Added sippreg_unregister API function

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by juha-h** [comment]
Don't know why retest failed.

**Comment by sreimers** [comment]
You branch is behind main. Rebase or Merge should help.

**Comment by juha-h** [comment]
Thanks, now done and OK.

**Comment by sreimers** [comment]
How did you merge? Looks like the last main commits are now part of this [PR](https://github.com/baresip/re/compare/main...unregister). I see no merge conflicts but wonder if this merge nicely. Maybe a new branch/PR would be safer.

**Comment by juha-h** [comment]
Will try again.

**Pull request closed without merging**
