### PR TITLE
cmake: bump minimum version of OpenSSL to 1.1.1

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by sreimers** [comment]
We should update the readme, too: https://github.com/baresip/re#supported-versions-of-openssl

**Comment by alfredh** [comment]
I am also wondering if we should use pre-compiled OpenSSL for the CI.
It takes a long time to compile OpenSSL for each commit ...

**Comment by sreimers** [comment]
We use already cached builds like here: https://github.com/baresip/re/blob/main/.github/workflows/mingw.yml#L41-L47

**Comment by alfredh** [comment]
aha, that is great.

So we can also do the same for e.g. Android build ?

**Pull request merged**
