### PR TITLE
jbuf: use float ratio

### PR DESCRIPTION
**Pull request by sreimers**

### CODE REVIEW

**Comment by juha-h** [comment]
I tested this PR using
```
        replaceVariable("audio_jitter_buffer_type", "adaptive")
        replaceVariable("audio_jitter_buffer_delay", "0-20")

        replaceVariable("video_jitter_buffer_type", "adaptive")
        replaceVariable("video_jitter_buffer_delay", "1-50")
```
and didn't have issues with calls.  In video calls I got some of these:
```
05-21 16:57:03.216 28352 28473 D Baresip+ Lib: video: recv Picture Loss Indication (PLI)
```
but they probably are not related to this PR.

**Comment by sreimers** [comment]
Thanks for testing.

> 05-21 16:57:03.216 28352 28473 D Baresip+ Lib: video: recv Picture Loss Indication (PLI)

Are both clients baresip?

**Comment by juha-h** [comment]
> Are both clients baresip?

Yes, I have tested both using Debian and Android baresips.  I get more of those message when network is slower (mobile vs. local WiFi).

**Comment by alfredh** [comment]
please rebase to main, wait for CI, and merge to main ...

**Pull request merged**
