### PR TITLE
main: remove long async blocking

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by alfredh** [comment]
@sreimers or @juha-h if you agree, please merge to master.

**Comment by sreimers** [comment]
Sometimes a long async blocking hint is useful for debugging. Maybe make it depend to `#if (DEBUG_LEVEL >= 7)` instead of MAIN_DEBUG?

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Sometimes a long async blocking hint is useful for debugging. Maybe
> make it depend to `#if (DEBUG_LEVEL >= 7)` instead of MAIN_DEBUG?

I agree that long async blocking hint is useful to have.  Dependency on
DEBUG_LEVEL 7 would be fine.

**Comment by alfredh** [comment]
okay, I would like to suggest that this check is disabled by default.
it should only be enabled if explicitly compiled in, e.g. MAIN_DEBUG or DEBUG_LEVEL.

also, a threshold of 100ms seems a bit low. perhaps 500ms is better.

on embedded platforms, this warning comes up quite a lot due to slow CPU.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> also, a threshold of 100ms seems a bit low. perhaps 500ms is better.

Yes, 500ms would be better.

**Comment by alfredh** [comment]
please have a look at the last commit.

MAIN_DEBUG and TMR_DEBUG is off by default.

it can be enabled explicitly:

`make EXTRA_CFLAGS=-DMAIN_DEBUG=1`

**Pull request merged**
