### PR TITLE
ci/win: add ARM, ARM64 and x86

### PR DESCRIPTION
**Pull request by sreimers**

### CODE REVIEW

**Comment by alfredh** [comment]
We could also add containers to run testcode on ARM.

old example: https://github.com/baresip/retest/blob/main/.github/workflows/run-on-arch.yml

**Comment by alfredh** [comment]
there are some errors in the build:


```
C:\Program Files\OpenSSL\lib\libssl.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
C:\Program Files\OpenSSL\lib\libcrypto.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
```


perhaps the wrong Arch for the OpenSSL libs ?

**Comment by cspiel1** [comment]
Why building arm on windows?

**Comment by sreimers** [comment]
> Why building arm on windows?

We had recently some build errors for Windows ARM and RE_ATOMIC. The complete ARM ecosystem is growing, so it I think its useful to catch these ones early.

> perhaps the wrong Arch for the OpenSSL libs ?

Yes we need platform builds for OpenSSL, maybe we found a good source of prebuilt ones, or use cached builds.

**Comment by alfredh** [comment]
https://github.com/chocolatey/choco/issues/1803

it is also possible to compile on ARM with OpenSSL disabled.

**Comment by alfredh** [comment]
Implemented in: https://github.com/baresip/re/pull/855

**Pull request closed without merging**
