### PR TITLE
Adaptive jbuf

### PR DESCRIPTION
**Pull request by cspiel1**
This PR introduces an adaptive jitter buffer algorithm.

The existing jbuf is extended.
    
    - Make functions jbuf_get/jbuf_put thread safe.
    - Add silence flag that has to be set by application (baresip) after decoding.
    - Compute jitter like RFC3550 (RTP) or wireshark.
    - Increase number of packets during silence in jbuf_get() by returning nothing.
    - Reduce number of packets by a second immediate jbuf_get(). After decoding baresip drops a frame during silence to reduce the latency again.
    - Adds wish size for the start of the stream.
    - docs: add jbuf folder to docs with README and gnuplot

jbuf
This plot shows that with a view buffer manipulations (the red dots) the average buffer size (avbuftime) can be kept between the boundaries. At 10 seconds the network jitter starts and at 25 seconds the jitter disappears.

Related to baresip PR: https://github.com/baresip/baresip/pull/1112
Related to retest PR (inhibits travis success): https://github.com/baresip/retest/pull/6

Here is a detailed description of the algorithm. Should we move this markdown to the baresip wiki?
[README.md](https://github.com/cspiel1/re/blob/adaptive_jbuf/docs/jbuf/README.md)

And this jbuf.plot was used to generate the plot above and contains the description of the plot. Should we add a plot image to the markdown README.md and move the plot description from jbuf.plot also to the markdown?
[jbuf.plot](https://github.com/cspiel1/re/blob/adaptive_jbuf/docs/jbuf/jbuf.plot)

### CODE REVIEW

**Comment by cspiel1** [comment]
### A note for testing/generate such plots
Simulation of the network jitter is mentioned in the docs/jbuf/README.md that is added by this PR. The last view days I had to dig into the iproute2 netem user space tool and the sch_netem kernel module because netem seems to be buggy in ubuntu 18.04 with kernel 4.15.0-123-generic. And after a system upgrade I had to notice this.

The RTP stream had a lot of reordered and very late packets making it impossible for the jbuf to handle this adequately.
Finally I found that the first chunk of this kernel commit brings the solution:
```
commit eadd1befdd778a1eca57fad058782bd22b4db804
Author: Aleksandr Nogikh <nogikh@google.com>
Date:   Wed Oct 28 17:07:31 2020 +0000

    netem: fix zero division in tabledist
```
That was:
```
-               return ((rnd % (2 * sigma)) + mu) - sigma;
+               return ((rnd % (2 * (u32)sigma)) + mu) - sigma;
```
After building the module net/sched with this fixed line I could re-activate my beautiful plots.

**Comment by sreimers** [comment]
please prevent force-push, its easier to review normal commits and the changes. for cleanup we can squash the pull request afterwards (if necessary).

**Comment by cspiel1** [comment]
Added two commits that avoids RTP packet drops.

**Comment by cspiel1** [comment]
@sreimers Again in this PR I am looking for a solution to make travis happy. Baresip/re builds depend on baresip/retest and vice versa. Is it possible with github/travis to specify in a PR a branch for other repos the travis build depends on? It would be nice to make travis happy without having to change the .travis.yml. Maybe by adding some Env Variables in the .travis.yml which can be set in the PR?

**Comment by sreimers** [comment]
> Again in this PR I am looking for a solution to make travis happy

i have already thought about that, i will test different approaches, maybe I find a nice solution. First I have to migrate retest from travis to github actions.

**Comment by cspiel1** [comment]
> > Again in this PR I am looking for a solution to make travis happy
> 
> i have already thought about that, i will test different approaches, maybe I find a nice solution. First I have to migrate retest from travis to github actions.
> 
> It looks like there is already a nice github action for our needs: https://github.com/marketplace/actions/github-action-build-chain-cross-repo-builds (i will take a closer look at this)

Fine! A minute ago I saw your newest commits belong the github actions.

**Comment by cspiel1** [comment]
Sorry! Had to push force because the master already changed and I made a rebase.
But only added one commit like stated by Alfred. This should be squashed with an earlier commit before the merge.

**Comment by cspiel1** [comment]
I convert this PR to draft because before a merge I have to squash some of the commits to make a clean git log. And maybe we move the jbuf to baresip.

**Comment by alfredh** [comment]
I have tested this patch with both fixed+adaptive type.
it seems to work fine, and does not introduce any unexpected errors.

the PR can be merged to master (@sreimers )

**Comment by cspiel1** [comment]
Thanks Alfred! I want to make the commit history cleaner first. Then will set the PR to active for merging.

**Comment by cspiel1** [comment]
@sreimers I pushed a fix in retest. Please could you trigger the tests here?

**Comment by sreimers** [comment]
> Oh, they started just now after I added a comment. Adding a comment triggers the tests?

I saw it, and re-triggered fast ;-)

**Comment by cspiel1** [comment]
Thanks!

**Pull request merged**
