### PR TITLE
dialog: fix rtags of forking INVITE

### PR DESCRIPTION
**Pull request by maximilianfridrich**
Resolves: https://github.com/baresip/baresip/issues/2819

### CODE REVIEW

**Comment by maximilianfridrich** [comment]
A similar PR (#947) resulted in no ACKs being sent in some scenarios - see https://github.com/baresip/baresip/issues/2772.

I tested this patch with the attached SIPP scenario ([bob_100rel_hold.txt](https://github.com/baresip/re/files/13558773/bob_100rel_hold.txt)) and the BareSIP selftest (which checks for pending ACKs).

Still, ideally, this patch could be tested in a few different setups to ensure that ACKs are always sent correctly.

**Comment by cspiel1** [comment]
@maximilianfridrich please could you add a retest for re-INVITE which also checks that an ACK is sent/received?

**Comment by maximilianfridrich** [comment]
Apparently there's still issues with ACKs to re-INVITEs, as stated by juha-h in https://github.com/baresip/baresip/issues/2819. I have looked into that in the past and could not find the cause. I will try again.

**Comment by maximilianfridrich** [comment]
I have finally found the ACK issue!

The issue was that the `pl` structs in `dlg->route` are initialized to point to a memory address within `dlg->mb`. In my patch I re-initialize `dlg->mb` and therefore the pointers in `dlg->route` were no longer valid. Now, after `dlg->mb` is reset in `sip_dialog_update`, `dlg->route` is also re-set to point into the new `mbuf`.

**Comment by cspiel1** [comment]
This test could help to detect missing ACKs: https://github.com/baresip/re/pull/1027

**Comment by sreimers** [comment]
@maximilianfridrich can you rebase against main to check if ACK tests are passed.

**Comment by maximilianfridrich** [comment]
@sreimers Done. Looks good.

**Comment by sreimers** [comment]
Thanks!

**Pull request merged**
